/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#006c49",
        "surface-tint": "#4edea3",
        "tertiary-container": "#b090ff",
        "surface-bright": "#31394d",
        "outline-variant": "#3c4a42",
        "on-primary-container": "#00422b",
        "inverse-surface": "#dae2fd",
        "error": "#ffb4ab",
        "secondary": "#89ceff",
        "tertiary": "#d0bcff",
        "secondary-fixed-dim": "#89ceff",
        "on-error": "#690005",
        "on-primary-fixed": "#002113",
        "surface-container-high": "#222a3d",
        "secondary-container": "#00a2e6",
        "outline": "#86948a",
        "primary-fixed": "#6ffbbe",
        "on-secondary-container": "#00344e",
        "surface-container": "#171f33",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#23005c",
        "on-tertiary-fixed-variant": "#5516be",
        "surface-container-lowest": "#060e20",
        "on-secondary": "#00344d",
        "primary-container": "#10b981",
        "error-container": "#93000a",
        "on-secondary-fixed": "#001e2f",
        "surface-container-highest": "#2d3449",
        "surface": "#0b1326",
        "inverse-on-surface": "#283044",
        "on-primary": "#003824",
        "on-tertiary-container": "#4600a7",
        "primary-fixed-dim": "#4edea3",
        "tertiary-fixed-dim": "#d0bcff",
        "surface-variant": "#2d3449",
        "on-background": "#dae2fd",
        "primary": "#4edea3",
        "on-tertiary": "#3c0091",
        "on-surface-variant": "#bbcabf",
        "surface-container-low": "#131b2e",
        "on-surface": "#dae2fd",
        "tertiary-fixed": "#e9ddff",
        "background": "#0b1326",
        "on-primary-fixed-variant": "#005236",
        "surface-dim": "#0b1326",
        "secondary-fixed": "#c9e6ff",
        "on-secondary-fixed-variant": "#004c6e"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        xs: "4px",
        "2xl": "64px",
        unit: "4px",
        lg: "24px",
        md: "16px",
        gutter: "24px",
        xl: "40px",
        margin: "32px",
        sm: "8px"
      },
      fontFamily: {
        "headline-lg": ["Manrope", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "stats-xl": ["Manrope", "sans-serif"],
        // Legacy aliases for old components that reference these
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "stats-xl": ["40px", { lineHeight: "1", letterSpacing: "-0.03em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
